spring:
  application:
    name:
      spring-file-upload

  servlet:
    multipart:
      enabled: true
      max-file-size: 1MB
      max-request-size: 10MB

  datasource:
    url: jdbc:postgresql://localhost:5432/file-upload
    username: spring-file-upload
    password: thy168
    driver-class-name: org.postgresql.Driver

    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        ddl-auto: update