spring:
  application:
    name:
      spring-file-upload

  servlet:
    multipart:
      enabled: true
      max-file-size: 1MB
      max-request-size: 10MB

  datasource:
    url: jdbc:h2:mem:file-upload
    username: sa
    password:
    driverClassName: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true